In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\vinto\appdata\local\programs\python\python312\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vinto\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinto\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\vinto\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\vinto\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [15]:
data = {'Name': ['Vinto', 'Vithu'], 'Age': [20, 19]}
df = pd.DataFrame(data)

In [29]:
lst = [['Vinto', 20], ['Vithu', 19]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

In [30]:
df.head()

    Name  Age
0  Vinto   20
1  Vithu   19

In [31]:
df.tail()

    Name  Age
0  Vinto   20
1  Vithu   19

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [33]:
df.describe()

             Age
count   2.000000
mean   19.500000
std     0.707107
min    19.000000
25%    19.250000
50%    19.500000
75%    19.750000
max    20.000000

In [34]:
df['Name']
df[['Name', 'Age']]

    Name  Age
0  Vinto   20
1  Vithu   19

In [37]:
df.loc[0]
df.iloc[1]

Name    Vithu
Age        19
Name: 1, dtype: object

In [38]:
df[df['Age'] > 25]

Empty DataFrame
Columns: [Name, Age]
Index: []

In [69]:
df['Gender'] = ['F', 'M']

In [70]:
df.drop('Age', axis=1, inplace=True)

KeyError: "['Age'] not found in axis"

In [71]:
df.isnull()

   Gender
0   False
1   False

In [72]:
df.dropna()

  Gender
0      F
1      M

In [73]:
df.fillna(0)

  Gender
0      F
1      M

In [74]:
df.groupby('Gender') ['Age'].mean()

KeyError: 'Column not found: Age'

In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df.to_csv('output.csv', index=False)

In [ ]:
df.sort_values('Age')

In [ ]:
df['Age'].apply9lambda x: x + 1)

In [ ]:
df['Name'].unique()

In [ ]:
df['Age'].value_counts()

In [ ]:
df.drop('Age', axis=1, inplace=True)

In [ ]:
df.isnull()

In [ ]:
import pandas as pd

In [ ]:
In [3]: s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [ ]:
In [4]: s
Out[4]: